import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { NextAuthProvider } from "./Providers";
 import { ToastContainer } from 'react-toastify';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

//  <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}></body>
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
    <body suppressHydrationWarning={true}>
    <NextAuthProvider>
      <Navbar></Navbar>
        {children}
      <Footer></Footer>
        <ToastContainer />
    </NextAuthProvider>
      </body>
    </html>
  );
}

